# configuration to setup readthedocs
version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
sphinx:
  configuration: docs/conf.py
# note:
#   disable PDF and EPUB which break during LaTeX
#   generation because of `redoc.js` script not found
#formats: all
formats:
  - htmlzip
  #- pdf
  #- epub
python:
  install:
    - requirements: requirements-sys.txt
    - requirements: requirements.txt    # required for OpenAPI generation
    - requirements: requirements-doc.txt
#    - method: pip
#      path: .
#      extra_requirements:
#        - docs
