PERMISSION_READ = u'read'
PERMISSION_READ_MATCH = u'read-match'
PERMISSION_WRITE = u'write'
PERMISSION_WRITE_MATCH = u'write-match'
PERMISSION_ACCESS = u'access'

PERMISSION_GET_CAPABILITIES = u'getcapabilities'
PERMISSION_GET_MAP = u'getmap'
PERMISSION_GET_FEATURE_INFO = u'getfeatureinfo'
PERMISSION_GET_LEGEND_GRAPHIC = u'getlegendgraphic'
PERMISSION_GET_METADATA = u'getmetadata'
PERMISSION_GET_FEATURE = u'getfeature'
PERMISSION_DESCRIBE_FEATURE_TYPE = u'describefeaturetype'
PERMISSION_DESCRIBE_PROCESS = u'describeprocess'
PERMISSION_EXECUTE = u'execute'
PERMISSION_LOCK_FEATURE = u'lockfeature'
PERMISSION_TRANSACTION = u'transaction'

permissions_supported = frozenset([
    PERMISSION_READ,
    PERMISSION_READ_MATCH,
    PERMISSION_WRITE,
    PERMISSION_WRITE_MATCH,
    PERMISSION_ACCESS,
    PERMISSION_GET_CAPABILITIES,
    PERMISSION_GET_MAP,
    PERMISSION_GET_FEATURE_INFO,
    PERMISSION_GET_LEGEND_GRAPHIC,
    PERMISSION_GET_METADATA,
    PERMISSION_GET_FEATURE,
    PERMISSION_DESCRIBE_FEATURE_TYPE,
    PERMISSION_DESCRIBE_PROCESS,
    PERMISSION_EXECUTE,
    PERMISSION_LOCK_FEATURE,
    PERMISSION_TRANSACTION,
])
