
user root;

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        off;
    keepalive_timeout  65;
    server {
        listen       80;
        server_name  localhost;

        location /magpie1/ {
            proxy_pass http://magpie1:2001/;
            proxy_set_header Host $host;
        }
        location /magpie2/ {
            proxy_pass http://magpie2:2001/;
            proxy_set_header Host $host;
        }
        location /magpie3/ {
            proxy_pass http://magpie3:2001/;
            proxy_set_header Host $host;
        }
    }
}
