# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Pull Request Labeler
on: 
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  label:
    permissions:
      # see: https://github.com/actions/labeler/issues/870
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: "0"
    - uses: actions/labeler@v4.3.0
      with:
        sync-labels: ''
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
