# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Pull Request Labeler
on:
  # https://github.com/actions/labeler#recommended-permissions
  pull_request_target:
    types: 
      - edited
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  label:
    # Skip for Dependabot - labels are already applied via dependabot.yml config
    if: github.actor != 'dependabot[bot]'
    permissions:
      # see: https://github.com/actions/labeler/issues/870
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out Repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: "0"
    - name: Label
      uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7.0.0
      with:
        sync-labels: false
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
